name: Lighting 

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "25 15 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Light
        run: |
          git config --local user.email "160697994+bethatguyad@users.noreply.github.com"
          git config --local user.name "bethatguyad"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "update!"
          git push
